package by.kutovoy.satellite.jFrames;

import by.kutovoy.satellite.enums.Icons;
import by.kutovoy.satellite.enums.ControlParameters;
import by.kutovoy.satellite.positions.NullPosition;
import by.kutovoy.satellite.positions.NullScale;
import java.awt.Dimension;

/**
 *
 * @author dmitry
 */
public class Control extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Control() {
        initComponents();                                       //инициализация всех компанентов
        this.btnSceneDown.setIcon(Icons.BTN_ICON_DOWN);         //добавление иконки к каждой кнопке; 6 штук
        this.btnSceneLeft.setIcon(Icons.BTN_ICON_LEFT);
        this.btnSceneRight.setIcon(Icons.BTN_ICON_RIGHT);
        this.btnSceneUp.setIcon(Icons.BTN_ICON_UP);
        this.btnZoomUp.setIcon(Icons.BTN_ICON_ZOOM_UP);
        this.btnZoomDown.setIcon(Icons.BTN_ICON_ZOOM_DOWN);

        this.btnSceneDown.setText("");                          //обнуление текста; 4 шт
        this.btnSceneLeft.setText("");
        this.btnSceneRight.setText("");
        this.btnSceneUp.setText("");
        
        //указание размера кнопок
        this.btnSceneDown.setPreferredSize(new Dimension(ControlParameters.getBTN_WIDTH(), ControlParameters.getBTN_HEIGHT()));
        this.btnSceneLeft.setPreferredSize(new Dimension(ControlParameters.getBTN_WIDTH(), ControlParameters.getBTN_HEIGHT()));
        this.btnSceneRight.setPreferredSize(new Dimension(ControlParameters.getBTN_WIDTH(), ControlParameters.getBTN_HEIGHT()));
        this.btnSceneUp.setPreferredSize(new Dimension(ControlParameters.getBTN_WIDTH(), ControlParameters.getBTN_HEIGHT()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSceneDown = new javax.swing.JButton();
        btnSceneUp = new javax.swing.JButton();
        btnSceneRight = new javax.swing.JButton();
        btnSceneLeft = new javax.swing.JButton();
        btnZoomDown = new javax.swing.JButton();
        btnZoomUp = new javax.swing.JButton();

        setTitle("Control");
        setBounds(new java.awt.Rectangle(0, 200, 0, 0));
        setResizable(false);

        btnSceneDown.setText("1");
        btnSceneDown.setPreferredSize(new java.awt.Dimension(42, 42));
        btnSceneDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSceneDownMouseClicked(evt);
            }
        });

        btnSceneUp.setText("1");
        btnSceneUp.setMaximumSize(new java.awt.Dimension(42, 42));
        btnSceneUp.setMinimumSize(new java.awt.Dimension(42, 42));
        btnSceneUp.setPreferredSize(new java.awt.Dimension(42, 42));
        btnSceneUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSceneUpActionPerformed(evt);
            }
        });

        btnSceneRight.setPreferredSize(new java.awt.Dimension(42, 42));
        btnSceneRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSceneRightMouseClicked(evt);
            }
        });

        btnSceneLeft.setText("1");
        btnSceneLeft.setPreferredSize(new java.awt.Dimension(42, 42));
        btnSceneLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSceneLeftMouseClicked(evt);
            }
        });

        btnZoomDown.setPreferredSize(new java.awt.Dimension(42, 42));
        btnZoomDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZoomDownMouseClicked(evt);
            }
        });

        btnZoomUp.setPreferredSize(new java.awt.Dimension(42, 42));
        btnZoomUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZoomUpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSceneLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSceneDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSceneRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnZoomDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSceneUp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZoomUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnZoomUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSceneRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSceneUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZoomDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSceneDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSceneLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSceneUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSceneUpActionPerformed
        NullPosition.setINSTANSE_Y(-ControlParameters.getY_STEP());         //при нажатии перемещение камеры вверх
    }//GEN-LAST:event_btnSceneUpActionPerformed

    private void btnZoomUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZoomUpMouseClicked
        NullScale.setScale(ControlParameters.getSCALE_STEP());         //при нажатии приближеня камеры
    }//GEN-LAST:event_btnZoomUpMouseClicked

    private void btnZoomDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZoomDownMouseClicked
        NullScale.setScale(-ControlParameters.getSCALE_STEP());         //при нажатии удаления камеры
    }//GEN-LAST:event_btnZoomDownMouseClicked

    private void btnSceneDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSceneDownMouseClicked
        NullPosition.setINSTANSE_Y(ControlParameters.getY_STEP());         //при нажатии перемещение камеры вниз
    }//GEN-LAST:event_btnSceneDownMouseClicked

    private void btnSceneRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSceneRightMouseClicked
        NullPosition.setINSTANSE_X(-ControlParameters.getX_STEP());         //при нажатии перемещение камеры вправо
    }//GEN-LAST:event_btnSceneRightMouseClicked

    private void btnSceneLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSceneLeftMouseClicked
        NullPosition.setINSTANSE_X(ControlParameters.getX_STEP());         //при нажатии перемещение камеры влево
    }//GEN-LAST:event_btnSceneLeftMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSceneDown;
    private javax.swing.JButton btnSceneLeft;
    private javax.swing.JButton btnSceneRight;
    private javax.swing.JButton btnSceneUp;
    private javax.swing.JButton btnZoomDown;
    private javax.swing.JButton btnZoomUp;
    // End of variables declaration//GEN-END:variables
}
