/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.kutovoy.satellite.jFrames;

import javax.swing.JFrame;

/**
 *
 * @author dmitry
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Ьутг
     */
    public Menu() {
        initComponents();

        this.control = new Control();
        this.satelliteAdd = new SatelliteAdd();
        this.satelliteRemove = new SatelliteRemove();

        this.control.setVisible(false);
        this.satelliteAdd.setVisible(false);
        this.satelliteRemove.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnControl = new javax.swing.JButton();
        textSatellite = new javax.swing.JLabel();
        btnSatelliteAdd = new javax.swing.JButton();
        btnSatelliteRemove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Satellite");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        btnControl.setText("Control");
        btnControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnControlMouseClicked(evt);
            }
        });

        textSatellite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSatellite.setText("Satellite");

        btnSatelliteAdd.setText("Add");
        btnSatelliteAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSatelliteAddMouseClicked(evt);
            }
        });

        btnSatelliteRemove.setText("Remove");
        btnSatelliteRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSatelliteRemoveMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Control");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textSatellite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSatelliteAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSatelliteRemove)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textSatellite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSatelliteAdd)
                    .addComponent(btnSatelliteRemove))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnControlMouseClicked
        if (control.isVisible()) {
            control.setVisible(false);
        } else {
            control.setVisible(true);
        }
    }//GEN-LAST:event_btnControlMouseClicked

    private void btnSatelliteAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSatelliteAddMouseClicked
        if (satelliteAdd.isVisible()) {
            satelliteAdd.setVisible(false);
        } else {
            satelliteAdd.setVisible(true);
        }
    }//GEN-LAST:event_btnSatelliteAddMouseClicked

    private void btnSatelliteRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSatelliteRemoveMouseClicked
        if (satelliteRemove.isVisible()){
            satelliteRemove.setVisible(false);
        }else{
            satelliteRemove.setVisible(true);
        }
    }//GEN-LAST:event_btnSatelliteRemoveMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }
    private JFrame control;
    private JFrame satelliteAdd;
    private JFrame satelliteRemove;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnControl;
    private javax.swing.JButton btnSatelliteAdd;
    private javax.swing.JButton btnSatelliteRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textSatellite;
    // End of variables declaration//GEN-END:variables
}
