package by.kutovoy.satellite.jFrames;

import by.kutovoy.satellite.beans.Satellite;
import by.kutovoy.satellite.beans.Satellites;
import by.kutovoy.satellite.enums.Sizes;
import by.kutovoy.satellite.enums.Textures;
import com.badlogic.gdx.graphics.Texture;

/**
 *
 * @author dmitry
 */
public class SatelliteAdd extends javax.swing.JFrame {

    /**
     * Creates new form SatelliteAdd
     */
    public SatelliteAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTextPositionX = new javax.swing.JTextField();
        SatelliteColorRed = new javax.swing.JRadioButton();
        SatelliteColorYellow = new javax.swing.JRadioButton();
        SatelliteColorGreen = new javax.swing.JRadioButton();
        textPositionX = new javax.swing.JLabel();
        TextSelectColor = new javax.swing.JLabel();
        btnSatellateAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        textError = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        textName = new javax.swing.JLabel();

        inputTextPositionX.setText("000");

        SatelliteColorRed.setText("Red");
        SatelliteColorRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SatelliteColorRedMouseClicked(evt);
            }
        });

        SatelliteColorYellow.setText("Yellow");
        SatelliteColorYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SatelliteColorYellowMouseClicked(evt);
            }
        });

        SatelliteColorGreen.setText("Green");
        SatelliteColorGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SatelliteColorGreenMouseClicked(evt);
            }
        });

        textPositionX.setText("set radius position");

        TextSelectColor.setText("Select color");

        btnSatellateAdd.setText("Add");
        btnSatellateAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSatellateAddMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        textError.setAutoscrolls(true);

        inputName.setText("name");

        textName.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSatellateAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextSelectColor)
                            .addComponent(SatelliteColorGreen)
                            .addComponent(textError)
                            .addComponent(SatelliteColorRed)
                            .addComponent(SatelliteColorYellow)
                            .addComponent(inputTextPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textPositionX)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(inputName, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTextPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPositionX))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSelectColor)
                    .addComponent(textName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SatelliteColorGreen)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SatelliteColorRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SatelliteColorYellow)
                .addGap(38, 38, 38)
                .addComponent(textError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSatellateAdd)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSatellateAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSatellateAddMouseClicked
        boolean valid = true;
        String error = "";
        Texture texture = null;
        if (SatelliteColorGreen.isSelected()) {
            texture = Textures.TEXTURE_GREEN_SATELLITE;
        }
        if (SatelliteColorRed.isSelected()) {
            texture = Textures.TEXTURE_RED_SATELLITE;
        }
        if (SatelliteColorYellow.isSelected()) {
            texture = Textures.TEXTURE_YELLOW_SATELLITE;
        }
        if (texture == null) {
            valid = false;
            error = error + "Choose color; \n";
        }
        int radius = 0;
        try {
            radius = Integer.parseInt(this.inputTextPositionX.getText());
        } catch (NumberFormatException nfe) {
            valid = false;
            error = error + "radius not a number; \n";
        }
        if (valid) {
            if (radius <= Sizes.PLANET.getX()/2) {
                valid = false;
                error = error + "radius is small; \n";
            }
        }
        String name = inputName.getText();
        if (Satellites.isNewName(name)) {
            if (name.equals("")) {
                valid = false;
                error = error + "Set name; ";
            }
        } else {
            valid = false;
            error = error + "Name alredy used; ";
        }
        if (valid) {
            Satellites.getINSTANCE().add(new Satellite(radius, texture, name));
        }
        textError.setText(error);


    }//GEN-LAST:event_btnSatellateAddMouseClicked

    private void SatelliteColorGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SatelliteColorGreenMouseClicked
        SatelliteColorGreen.setSelected(true);
        SatelliteColorYellow.setSelected(false);
        SatelliteColorRed.setSelected(false);
    }//GEN-LAST:event_SatelliteColorGreenMouseClicked

    private void SatelliteColorRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SatelliteColorRedMouseClicked
        SatelliteColorGreen.setSelected(false);
        SatelliteColorYellow.setSelected(false);
        SatelliteColorRed.setSelected(true);
    }//GEN-LAST:event_SatelliteColorRedMouseClicked

    private void SatelliteColorYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SatelliteColorYellowMouseClicked
        SatelliteColorGreen.setSelected(false);
        SatelliteColorYellow.setSelected(true);
        SatelliteColorRed.setSelected(false);
    }//GEN-LAST:event_SatelliteColorYellowMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        inputTextPositionX.setText("000");
        inputName.setText("name");
        SatelliteColorGreen.setSelected(false);
        SatelliteColorRed.setSelected(false);
        SatelliteColorYellow.setSelected(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SatelliteColorGreen;
    private javax.swing.JRadioButton SatelliteColorRed;
    private javax.swing.JRadioButton SatelliteColorYellow;
    private javax.swing.JLabel TextSelectColor;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSatellateAdd;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputTextPositionX;
    private javax.swing.JLabel textError;
    private javax.swing.JLabel textName;
    private javax.swing.JLabel textPositionX;
    // End of variables declaration//GEN-END:variables
}
